config/routes.rb
Rails.application.routes.default_url_options[:host] = 'rorlab.org'

Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root "welcome#index"

  get 'newsletters/unsubscribe/:email' => 'newsletters#unsubscribe', as: :eunsubscribe_newsletters
  get 'newsletters/subscribe/(:email)' => 'newsletters#subscribe'
  post 'newsletters/subscribe/(:email)' => 'newsletters#subscribe', as: :esubscribe_newsletters
  post 'newsletters/:user_id/subscribe' => 'newsletters#subscribe', as: :subscribe_newsletters
  put 'newsletters/:user_id/unsubscribe' => 'newsletters#unsubscribe', as: :unsubscribe_newsletters
  get 'newsletters/new/subscribe' => 'newsletters#new_subscribe', as: :new_subscribe_newsletters
  resources :newsletters do
    member do
      get 'preview'
      get 'sendmail'
    end
    resources :articles
  end


  post 'glossaries/:glossary_id/glossary_definitions/:id/like_toggle' => 'glossary_definitions#like_toggle', as: :like_glossary_definition
  match "/delayed_job" => DelayedJobWeb, :anchor => false, via: [:get, :post]

  get 'tags', to: 'tags#list'
  get 'purchase_requests/confirm_request/:id' => 'purchase_requests#confirm_request_toggle', as: :confirm_purchase

  # Info routing
  get 'info/about', as: :about
  get 'info/howto', as: :howto
  get 'info/copyright', as: :copyright
  get 'info/security', as: :security
  get 'info/contributor', as: :contributors

  get 'podcasts/grap' => 'podcasts#grap'
  get 'events/upcoming'
  # Exception routing
  get '/404', to: 'errors#not_found'
  get '/500', to: 'errors#server_error'

  # Devise routing
  devise_for :users, controllers: { registrations: 'users/registrations' }
  resource :user_profile

  # Resources routing
  resources :schedules do
    resources :appliers do
      member do
        put 'accept'
        put 'recommand'
      end
    end
  end

  concern :commentable do
    resources :comments
  end
  resources :favlinks, :codebanks, :rblogs, :events, :purchase_requests, :group_purchases, :courses, :lectures, :schedules, :websites, concerns: :commentable

  resources :glossaries, concerns: :commentable do
    member do
      post 'tag'
    end
    resources :glossary_definitions
  end

  resources :courses do
    resources :lectures
  end

  resources :group_purchases do
    resources :purchase_requests
  end

  resources :plazas
  resources :bundlelinks do
    resources :favlinks
  end
  resources :favlinks
  resources :bulletins do
    resources :posts
  end
  resources :questions do
    resources :answers
  end

  resources :podcasts, only: [ :index, :show ], concerns: :commentable

  get 'weeklynews/index', as: 'weeklynews'
  get 'weeklynews/grap', as: 'weeklynews_grap'


  # API routing
  namespace :api do
    resources :questions do
      resources :answers
    end
  end

end

app/views/layouts/shared/_bottom_menu.html.erb
<div class='bottom_menu'>

<div class='row'>
  <div class='col-md-3'>
    <div style="overflow:auto;">
      <%= image_tag 'rorlab_logo_158x158.png', height: 75, style:'float:left;margin-right:1em;' %>
      <p>루비/루비온레일스를 위한 커뮤니티. </p>
      <p>since 2011</p>
    </div>
    <div class='py-3 mb-3'>
      <%= link_to fas_icon_text('users', 'Contributors'), contributors_path, class: 'btn btn-primary btn-lg btn-block py-4' %>
    </div>
  </div>
  <div class='col-md-3'>
    <div class='menu_title'><%= fas_icon_text "bullhorn", "최근 공지 및 새소식" %></div>
    <ul class='section'>
    <% @news = Post.where(bulletin_id: [ 1, 2]).recent %>
    <% @news.each do | post | %>
      <li><%= link_to post.title, bulletin_post_path(post.bulletin, post) %>
      <small title='<%= post.created_at %>' data-toggle="tooltip" class='text-muted'><%= time_ago_in_words(post.created_at) %>전 작성</small></li>
    <% end %>
    </ul>
  </div>

  <div class='col-md-6'>
    <div class='row'>
      <div class='col-md-4 col-sm-4'>
        <div class='menu_title'><%= far_icon_text "calendar", "행사 및 일정" %></div>
        <ul class='section'>
          <% Schedule.all.order(id: :desc).limit(5).each do | schedule | %>
            <li><%= link_to schedule.name, schedule %></li>
          <% end %>
        </ul>
      </div>

      <div class='col-md-4 col-sm-4'>
        <div class='menu_title'><%= fas_icon_text "archive", "한글 및 문서화" %></div>
        <ul class='section'>
          <li><%= link_to '레일스가이드', 'http://guides.rorlab.org', target: '_blank' %></li>
          <li><%= link_to '초레가', 'https://www.railsguidebook.com/', target: '_blank' %></li>
          <li><%= link_to 'Railscasts', 'http://railscasts.com', target: '_blank' %></li>
          <li><%= link_to 'GoRails', 'https://gorails.com/', target: '_blank' %></li>
          <li><%= link_to 'Ruby Screencasts', 'https://www.driftingruby.com', target: '_blank' %></li>
          <li><%= link_to 'Ruby on Rails Tutorial', 'https://www.railstutorial.org/', target:'_blank' %></li>
        </ul>
      </div>

      <div class='col-md-4 col-sm-4'>
        <div class='menu_title'><%= fas_icon_text 'info-circle', '도움말' %></div>
        <ul class='section'>
          <li><%= link_to '소개말', about_path %></li>
          <li><%= link_to '웹사이트 사용법', howto_path %></li>
          <li><%= link_to '홈페이지 오류보고', "#" %></li>
          <li><%= link_to '개인정보보호', security_path %></li>
          <li><%= link_to '저작권보호', copyright_path %></li>
        </ul>
      </div>
    </div>
  </div>
</div>

</div>

app/views/layouts/shared/_fb_broadcast_panel.html.erb
<div class="card">
	<div class="card-body">
    <p>
      <strong style='font-size:1.5em;vertical-align:middle;'>페이스북에서 실시간 방송하기 : </strong>
      <button id="liveButton" class='btn btn-primary btn-sm'>
        Start Live Stream
      </button>
    </p>
      <b>주의:</b> 사용하기 전에 데스크톱에 OBS(<%= link_to "Open Broadcaster Software", "https://obsproject.com/download#mac", target: '_blank' %>)를 설치해 두어야 합니다. 데스트톱 브라우저 상에서만 사용할 수 있으며, 스마트디바이스에서는 페이스북 자체 <code>라이브방송</code>을 사용하세요.<br  />
      <b>사용법:</b> <%= link_to "유투브동영상", "https://youtu.be/EB72C6CxiO0", target: '_blank' %><br />
      <b>참고:</b> <%= link_to '페이스북으로 데스크탑 라이브 스트리밍 하기',  'http://blog.appkr.kr/work-n-play/facebook-live-streaming/', target: '_blank' %>

  </div>
</div>

<script>
  // 페이스북 SDK 임포트 및 초기화
  // https://developers.facebook.com/docs/javascript/quickstart
  // 에서 최신 스크립트를 확인하고 사용하시길 권장한다.
  // window.fbAsyncInit = function() {
  //   FB.init({
  //     appId: <%= Rails.application.credentials.dig(:facebook, :live_stream_app_id) %>,
  //     xfbml: true,
  //     version: 'v2.5'
  //   });
  // };

  // (function(d, s, id){
  //   var js, fjs = d.getElementsByTagName(s)[0];
  //   if (d.getElementById(id)) {return;}
  //   js = d.createElement(s); js.id = id;
  //   js.src = "//connect.facebook.net/en_US/sdk.js";
  //   fjs.parentNode.insertBefore(js, fjs);
  // }(document, 'script', 'facebook-jssdk'));

  // 페이스북 라이브 스트리밍 스타터
  // https://developers.facebook.com/docs/videos/live-video-api#golivedialog
  // 에서 최신 스크립트를 확인하고 사용하시길 권장한다.
  document.getElementById('liveButton').onclick = function() {
    FB.ui({
      display: 'popup',
      method: 'live_broadcast',
      phase: 'create',
    }, function(response) {
      if (!response.id) {
        alert('dialog canceled');
        return;
      }
      alert('stream url:' + response.secure_stream_url);
      FB.ui({
        display: 'popup',
        method: 'live_broadcast',
        phase: 'publish',
        broadcast_data: response,
      }, function(response) {
        alert("video status: \n" + response.status);
      });
    });
  };
</script>

app/views/layouts/shared/_nav.html.erb
<nav class="navbar navbar-dark bg-dark navbar-expand-lg fixed-top" style="background-color: #302a2a;">
  <div class="container">
    <a class="navbar-brand" href="#"><%= image_tag 'rorlab_logo_155x40_300dpi.png', class: 'd-inline-block align-top' %></a>
    <button class="navbar-toggler mr-1" type="button" data-toggle="collapse" data-target="#navbarToggleExternalContent" aria-controls="navbarToggleExternalContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarToggleExternalContent">
      <ul class="navbar-nav">
        <li class="nav-item <%= active_menu('welcome') %>"><%= link_to "Home", root_path, class: 'nav-link' %></li>
        <li class="nav-item <%= active_menu('plazas') %>"><%= link_to "Plaza", plazas_path, class: 'nav-link' %></li>
        <li class='nav-item dropdown <%= active_menu('posts') %>'>
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown1" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Bulletins
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown1">
            <% @bulletin_titles.each do |bulletin| %>
              <%= link_to bulletin, bulletin_posts_path(bulletin), class: "dropdown-item #{ params[:bulletin_id] == bulletin ? 'active' : '' }" %>
            <% end %>
            <div class="dropdown-divider"></div>
            <%= link_to fa_icon_text("newspaper", "뉴스레터"), newsletters_path, class: "dropdown-item #{ active_menu('newsletters', 'articles') }" %>

            <div class="dropdown-divider"></div>
            <%= link_to fas_icon_text("calendar", "RORLAB일정"), schedules_path, class: "dropdown-item #{active_menu('schedules', 'appliers')}" %>

            <div class="dropdown-divider"></div>
            <%= link_to fas_icon_text("shopping-cart", "공동구매"), group_purchases_path, class: "dropdown-item #{active_menu('group_purchases', 'purchase_requests')}" %>
          </div>
        </li>
        <li class='nav-item dropdown <%= active_menu('codebanks', 'podcasts', 'weeklynews', 'favlinks', 'questions') %>'>
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown2" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            DataRoom
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown2">  
            <%= link_to '루비와 레일스 웹서비스', websites_path, class: "dropdown-item #{active_menu("websites")}" %>
            <div class="dropdown-divider"></div>
            <%= link_to '레일스강좌', courses_path, class: "dropdown-item #{active_menu('courses', 'lectures')}" %>
            <%= link_to 'Codebanks', codebanks_path, class: "dropdown-item #{active_menu('codebanks')}" %>
            <%#= link_to 'Podcasts', podcasts_path, class: "dropdown-item #{active_menu('podcasts')}" %>
            <%= link_to '주간뉴스', weeklynews_path, class: "dropdown-item #{active_menu('weeklynews')}" %>
            <%= link_to "Favlinks", favlinks_path, class: "dropdown-item #{active_menu('favlinks')}" %>
            <%= link_to 'Q&A', questions_path, class: "dropdown-item #{active_menu('questions')}" %>
          </div>
        </li>
        <li class="nav-item <%= active_menu('rblogs') %>">
          <%= link_to 'rBlogs', rblogs_path, class: 'nav-link' %></li>
        <li class="nav-item <%= active_menu('glossaries') %>">
          <%= link_to 'Glossary', glossaries_path, class: 'nav-link' %></li>
      </ul>
      <ul class="navbar-nav ml-auto">
        <% if user_signed_in? %>
          <li class="nav-item dropdown <%= 'active' if devise_controller? %>">
            <a class="nav-link dropdown-toggle" href="#" id='navbarDropdown2' data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <%= user_profile current_user %>
              <%= current_user.account_name %>
              <b class="caret"></b>
            </a>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown2">
              <h6 class="dropdown-header">Level : <%= current_user.level %> / Point : <%= current_user.points %></h6>
              <h6 class="dropdown-header">Roles : <%= user_roles(current_user) %></h6>
              <div class="dropdown-divider"></div>
              <%= link_to "My Account", edit_user_registration_path, class: 'dropdown-item' %>
              <%= link_to "My Profile", (current_user.user_profile.nil? ? new_user_profile_path : edit_user_profile_path), class: 'dropdown-item' %>
            </div>
          </li>
          <li class='nav-item'>
            <%= link_to "Sign out", destroy_user_session_path, method: :delete, data: { confirm: "Are you sure?" }, class: 'nav-link' %>
          </li>
        <% else %>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown3" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Sign in
            </a>            
            <div class="dropdown-menu" aria-labelledby="navbarDropdown3">
              <%= link_to "with RORLa", new_user_session_path, class: "dropdown-item" %>
            </div>
          </li>
          <li class='nav-item'><%= link_to "Sign up", new_user_registration_path, class: 'nav-link' %></li>
        <% end %>
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</nav>

app/views/layouts/shared/_preview.html.erb
<div class="modal fade" id="previewModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content modal-content-one">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <h4 class="modal-title" id="myModalLabel">[Preview] <%= title %></h4>
      </div>
      <div class="modal-body">
        <div id="wmd-preview-<%= attribute %>" class='wmd-preview'></div>
        <div style='text-align:center;border-top:1px solid #eaeaea;padding-top:1em;'>
          <p>- The End of rBlog -</p>
          (Preview를 중단하려면 esc 키를 누르거나 우측 상단에 있는 &times; 표시를 클릭하세요.)
        </div>
      </div>
    </div>
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

app/views/layouts/shared/_promo.html.erb
<div class="promo alert alert-danger text-center">
  <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
  <h3>The AGAIN2011 Workshop<br /><small class='text-danger'>for Rails Beginners</small></h3>
  <p>
    기간 : 2016-06 ~ 2016-08<br/>
    시간 : 격주 일요일 오전 9시 ~ 12시<br />
    장소 : 토즈 강남2호점<br />
    주체 : RORLAB | 지원 : 네이버D2<br />
  </p>
  <p>
    <%= link_to "참가신청하기", "/schedules/1/appliers/new", class: 'btn btn-danger' %>
  </p>
</div>

app/views/layouts/shared/_railsguidebook_panel.html.erb
<div class="card">
	<div class="card-body">
		<div class="media">
      <%= link_to image_tag('rails_guide_cover.jpg', class: 'img-fluid rounded mr-3 d-none d-md-inline', alt: 'Gitbook'), "https://www.railsguidebook.com/" %>
      <%= image_tag('rails_guide_cover.jpg', width: '35%', class: 'img-fluid rounded mr-3 d-inline-block d-md-none', alt: 'Gitbook') %>
		  <div class="media-body">
		    <h5 class="mt-0"><%= link_to '초보자를 위한 레일스 가이드북', "https://www.railsguidebook.com/", target: '_blank' %></h5>
		    Gitbook(온라인 전자책)으로 작성된 레일스 안내서로 RORLAB에서 공동집필로 작성되었습니다.<hr>
		    그 외에도 초보자를 위한 <a href='http://www.gitbook.io/book/luciuschoi/exploring_devise' target='_blank'>"Devise 젬 파헤치기"</a>, <a href='http://www.gitbook.io/book/luciuschoi/foundblog' target='_blank'>"FoundBlog 따라하기"</a> 등이 있습니다.
		  </div>
		</div>
	</div>
</div>

app/views/layouts/shared/_screencasts_panel.html.erb
<div class="card">
  <div class="card-body">
    <div class="media">
      <%= link_to image_tag("youtube_channel.png", size: '107x140', class: 'mr-2'), "http://youtube.com/user/rorlabkr" %>
      <div class="media-body">
        <h4 class="media-heading">RORLab. 강의동영상 모음 Youtube Channel</h4>
        현재까지 RORLab.에서 진행되었던 강의동영상과 관련 동영상을 유튜브 채널로 재구성하였습니다.<hr>
        <div class='row'>
          <div class='col-md-6'>
            <ul>
              <li><%= link_to '시즌 1, Rails Guide', 'http://www.youtube.com/playlist?list=PLfFG7L-h1FSpOG7duwhp4q9ThZEzELLZ5' %></li>
              <li><%= link_to '시즌 2, Rails Guide', 'http://www.youtube.com/playlist?list=PLfFG7L-h1FSpSXaU-r0UVhW1efcwZl1g-' %></li>
              <li><%= link_to '시즌 3, Rails Guide', 'http://www.youtube.com/playlist?list=PLfFG7L-h1FSpwVKSLYtOUriFa7L3mPs6t' %></li>
              <li><%= link_to '시즌 4, Rails Guide', 'http://www.youtube.com/playlist?list=PLfFG7L-h1FSrotpAplTzHMKh_LnuT5pGX' %></li>
            </ul>
          </div>
          <div class='col-md-6'>
            <ul>
              <li><%= link_to 'AGAIN2011', 'https://www.youtube.com/playlist?list=PLfFG7L-h1FSq5jhEsDgL9txyglgEZLltq' %></li>
              <li><%= link_to 'Digging Deeper (시즌 4)', 'http://www.youtube.com/playlist?list=PLfFG7L-h1FSpR6rjK-oFnRqOK00A-romg' %></li>
              <li><%= link_to 'Live Coding', 'http://www.youtube.com/playlist?list=PLfFG7L-h1FSrTRMJP-uEVesVIE75pv7d4' %></li>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/shared/_sidebar.html.erb
<%= link_to  fab_icon_text('slack', "Slack 가입"), "https://join.slack.com/t/rorlab/shared_invite/enQtMzE3MTY1OTMzNjY1LTdkMjdjZjEzZDI5ZDJmZTYzODIzMWI4MDI5MTY0NjI4ZDE4ZGNkNDRmMGQ1ZjdkMTlmNjQ4YmM1MTFlOTQ3NWU", target: '_blank', class: 'btn btn-success btn-block mb-3' %>

<!-- 게시판 사이드바 -->
<%= render 'layouts/shared/sidebar/sidebar_for_posts' %>

<!-- 코드뱅크 사이드바 -->
<%= render 'layouts/shared/sidebar/sidebar_for_codebanks' %>

<!-- Q&A 사이드바 -->
<%= render 'layouts/shared/sidebar/sidebar_for_questions' %>

<!-- rBlog 사이드바 -->
<%= render 'layouts/shared/sidebar/sidebar_for_rblogs' %>

<!-- 뉴스레터 사이트바 -->
<%= render 'layouts/shared/sidebar/sidebar_for_newsletters' %>

<!-- 레일스강좌 사이드바 -->
<%= render 'layouts/shared/sidebar/sidebar_for_lectures' %>

<!-- Favlinks 사이드바 -->
<%= render 'layouts/shared/sidebar/sidebar_for_favlinks' %>

<!-- 용어집 사이드바 -->
<%= render 'layouts/shared/sidebar/sidebar_for_glossaries' %>

<!-- 루비와 레일스 웹서비스 사이드바 -->
<%= render 'layouts/shared/sidebar/sidebar_for_websites' %>

<!--Twitter Timeline-->
<%#= render 'layouts/shared/sidebar/sidebar_for_twitter' %>

app/views/layouts/shared/_weeklynews_panel.html.erb
<div class="card">
  <div class="card-body">
    <div class="row">
      <div class="col-xs-12 col-sm-3 col-md-3">
        <%= link_to weeklynews_path do %>
          <%= image_tag "rorlab_weekly.png", class: 'img-fluid', alt: "RORLab 주간뉴스" %>
        <% end %>
      </div>
      <div class="col-xs-12 col-sm-9 col-md-9">
        RORLab 주간뉴스는 매주 <strong>루비</strong>와 <strong>루비온레일스</strong>에 대한 정보를 전달합니다.
      </div>
    </div>
  </div>
</div>

app/views/layouts/shared/_welcome_panel.html.erb
<div class="jumbotron">
  <div class="container">
    <h2>
      RORLAB에 오신 것을 환영합니다.<br />
      <small>
        <div class="btn-group" role="group" aria-label="Basic example">
          <button type="button" class="btn btn-danger btn-sm label label-danger">Ruby</button>
          <button type="button" class="btn btn-info btn-sm label label-secondary">v<%= RUBY_VERSION %></button>
        </div>
        <div class="btn-group" role="group" aria-label="Basic example">
          <button type="button" class="btn btn-danger btn-sm label label-danger">Rails</button>
          <button type="button" class="btn btn-info btn-sm label label-secondary">v<%= Rails::VERSION::STRING %></button>
        </div>
      </small>
    </h2>
    <p>: Ruby on Rails Korean Study Group with Free Offline Lectures</p>
    <hr style="border:1px solid #850000;">
      <% if user_signed_in? %>
        <p>Hello, <em><%= current_user.account_name.capitalize! %></em></p>
        <%= link_to fas_icon_text("sign-out-alt", "로그아웃"), destroy_user_session_path, method: :delete, data: { confirm: "Are you sure?"}, class: 'btn btn-primary' %>
      <% else %>
        <%= link_to fas_icon_text("sign-in-alt", "로그인"), new_user_session_path, class: 'btn btn-primary' %>
        <%= link_to fas_icon_text("users", "회원가입"), new_user_registration_path, class: 'btn btn-success d-none d-sm-inline-block ' %>
      <% end %>
      <%= link_to fas_icon_text("search", "용어집검색"), glossaries_path, class: 'btn btn-success float-right' %>
  </div>
</div>