config/routes.rb
Rails.application.routes.default_url_options[:host] = 'rorlab.org'

Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root "welcome#index"

  get 'newsletters/unsubscribe/:email' => 'newsletters#unsubscribe', as: :eunsubscribe_newsletters
  get 'newsletters/subscribe/(:email)' => 'newsletters#subscribe'
  post 'newsletters/subscribe/(:email)' => 'newsletters#subscribe', as: :esubscribe_newsletters
  post 'newsletters/:user_id/subscribe' => 'newsletters#subscribe', as: :subscribe_newsletters
  put 'newsletters/:user_id/unsubscribe' => 'newsletters#unsubscribe', as: :unsubscribe_newsletters
  get 'newsletters/new/subscribe' => 'newsletters#new_subscribe', as: :new_subscribe_newsletters
  resources :newsletters do
    member do
      get 'preview'
      get 'sendmail'
    end
    resources :articles
  end


  post 'glossaries/:glossary_id/glossary_definitions/:id/like_toggle' => 'glossary_definitions#like_toggle', as: :like_glossary_definition
  match "/delayed_job" => DelayedJobWeb, :anchor => false, via: [:get, :post]

  get 'tags', to: 'tags#list'
  get 'purchase_requests/confirm_request/:id' => 'purchase_requests#confirm_request_toggle', as: :confirm_purchase

  # Info routing
  get 'info/about', as: :about
  get 'info/howto', as: :howto
  get 'info/copyright', as: :copyright
  get 'info/security', as: :security
  get 'info/contributor', as: :contributors

  get 'podcasts/grap' => 'podcasts#grap'
  get 'events/upcoming'
  # Exception routing
  get '/404', to: 'errors#not_found'
  get '/500', to: 'errors#server_error'

  # Devise routing
  devise_for :users, controllers: { registrations: 'users/registrations' }
  resource :user_profile

  # Resources routing
  resources :schedules do
    resources :appliers do
      member do
        put 'accept'
        put 'recommand'
      end
    end
  end

  concern :commentable do
    resources :comments
  end
  resources :favlinks, :codebanks, :rblogs, :events, :purchase_requests, :group_purchases, :courses, :lectures, :schedules, :websites, concerns: :commentable

  resources :glossaries, concerns: :commentable do
    member do
      post 'tag'
    end
    resources :glossary_definitions
  end

  resources :courses do
    resources :lectures
  end

  resources :group_purchases do
    resources :purchase_requests
  end

  resources :plazas
  resources :bundlelinks do
    resources :favlinks
  end
  resources :favlinks
  resources :bulletins do
    resources :posts
  end
  resources :questions do
    resources :answers
  end

  resources :podcasts, only: [ :index, :show ], concerns: :commentable

  get 'weeklynews/index', as: 'weeklynews'
  get 'weeklynews/grap', as: 'weeklynews_grap'


  # API routing
  namespace :api do
    resources :questions do
      resources :answers
    end
  end

end

app/models/schedule.rb
# == Schema Information
#
# Table name: schedules
#
#  id             :integer          not null, primary key
#  user_id        :integer
#  name           :string(255)      not null
#  info           :text(65535)
#  venue          :string(255)
#  start_date     :datetime
#  end_date       :datetime
#  repeating      :boolean
#  charged        :boolean          default(FALSE)
#  charge_amount  :integer          default(0)
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#  pre_start_date :datetime
#  pre_end_date   :datetime
#

class Schedule < ActiveRecord::Base

  resourcify
  include Authority::Abilities

  belongs_to :user
  has_many :appliers, dependent: :destroy
  has_many :comments, as: :commentable, dependent: :destroy
  has_many :recommandations, dependent: :destroy
  

  validates :name, presence: true, uniqueness: true
end

app/controllers/schedules_controller.rb
# == Schema Information
#
# Table name: schedules
#
#  id             :integer          not null, primary key
#  user_id        :integer
#  name           :string(255)      not null
#  info           :text(65535)
#  venue          :string(255)
#  start_date     :datetime
#  end_date       :datetime
#  repeating      :boolean
#  charged        :boolean          default(FALSE)
#  charge_amount  :integer          default(0)
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#  pre_start_date :datetime
#  pre_end_date   :datetime
#

class SchedulesController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :udpate]
  before_action :set_schedule, only: [:show, :edit, :update, :destroy]

  # GET /schedules
  # GET /schedules.json
  def index
    @schedules = Schedule.order( created_at: :desc).paginate(page: params[:page], per_page: 10)
  end

  # GET /schedules/1
  # GET /schedules/1.json
  def show
  end

  # GET /schedules/new
  def new
    authorize_action_for Schedule
    @schedule = Schedule.new
  end

  # GET /schedules/1/edit
  def edit
    authorize_action_for @schedule
  end

  # POST /schedules
  # POST /schedules.json
  def create
    authorize_action_for Schedule
    @schedule = current_user.schedules.new(schedule_params)

    respond_to do |format|
      if @schedule.save
        format.html { redirect_to @schedule, notice: 'Schedule was successfully created.' }
        format.json { render :show, status: :created, location: @schedule }
      else
        format.html { render :new }
        format.json { render json: @schedule.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /schedules/1
  # PATCH/PUT /schedules/1.json
  def update
    authorize_action_for @schedule
    respond_to do |format|
      if @schedule.update(schedule_params)
        format.html { redirect_to @schedule, notice: 'Schedule was successfully updated.' }
        format.json { render :show, status: :ok, location: @schedule }
      else
        format.html { render :edit }
        format.json { render json: @schedule.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /schedules/1
  # DELETE /schedules/1.json
  def destroy
    authorize_action_for @schedule
    @schedule.destroy
    respond_to do |format|
      format.html { redirect_to schedules_url, notice: 'Schedule was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_schedule
      @schedule = Schedule.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def schedule_params
      params.require(:schedule).permit(:user_id, :name, :info, :venue, :pre_strat_date, :pre_end_date, :start_date, :end_date, :repeating, :charged, :charge_amount)
    end
end

app/helpers/schedules_helper.rb
# == Schema Information
#
# Table name: schedules
#
#  id             :integer          not null, primary key
#  user_id        :integer
#  name           :string(255)      not null
#  info           :text(65535)
#  venue          :string(255)
#  start_date     :datetime
#  end_date       :datetime
#  repeating      :boolean
#  charged        :boolean          default(FALSE)
#  charge_amount  :integer          default(0)
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#  pre_start_date :datetime
#  pre_end_date   :datetime
#

module SchedulesHelper

  def lecture_type(bool)
    bool ? "유료" : "무료"
  end
end

app/views/schedules/_form.html.erb
<%= render "layouts/shared/preview", title: @schedule.name, attribute: :info %>

<%= simple_form_for(@schedule) do |f| %>
  <%= f.error_notification %>

  <div class="row">
    <div class="col-sm-7">
      <%= f.input :name %>
      <%= f.input :info, :as => :pagedown, input_html: { rows: 17 } %>
    </div>
    <div class="col-sm-5">
      <%= f.input :venue %>
      <%= f.input :pre_start_date %>
      <%= f.input :pre_end_date %>
      <%= f.input :start_date %>
      <%= f.input :end_date %>
      <div class="row">
        <div class="col-xs-4">
          <%= f.input :repeating %>
        </div>
        <div class="col-xs-8">
          <%= f.input :charged %>
          <%= f.input :charge_amount %>
        </div>
      </div>
    </div>
  </div>

  <div class="form-actions">
    <%= button_tag(type: 'submit', class: "btn btn-success") do %>
      <%= awesome_icon_label "save", "저장" %>
    <% end %>
    <%= link_to far_icon_text('eye', '보기'), @schedule, class: 'btn btn-default' if @schedule.persisted? %>
    <%= link_to far_icon_text('calendar', 'RORLAB일정'), schedules_path, class: 'btn btn-default' %>
  </div>

<% end %>

app/views/schedules/edit.html.erb
<h2>일정변경</h2>
<br />
<%= render 'form' %>

app/views/schedules/index.html.erb
<h2>RORLAB일정</h2>
<br />
<div class="card table-responsive-md">
  <table class='table table-bordered mb-0'>
    <thead>
      <tr>
        <th class='text-center'><%= t("activerecord.attributes.schedule.name") %></th>
        <th class='text-center'><%= t("activerecord.attributes.schedule.venue") %></th>
        <th class='text-center'><%= t("activerecord.attributes.schedule.start_date") %></th>
        <th class='text-center'>수강료</th>
        <th class='text-center'>데이터작업</th>
      </tr>
    </thead>

    <tbody>
      <% if @schedules.empty? %>
        <tr><td class='text-center text-primary'><%= awesome_icon_label "exclamation-triangle", '아직 등록된 일정이 없습니다.' %></td></tr>
      <% end %>
      <% @schedules.each do |schedule| %>
        <tr>
          <td><%= link_to schedule.name, schedule %> <small><%= schedule.appliers.size if user_signed_in? && current_user.has_role?(:contributor) %></small></td>
          <td class='text-center'><%= schedule.venue %></td>
          <td class='text-center'><%= schedule.start_date %></td>
          <td class='text-center'><%= schedule.charged ? number_to_currency(schedule.charge_amount) : lecture_type(schedule.charged) %></td>
          <td class='text-center'>
            <%= link_to icon_button('eye', kind: :success), schedule %>
            <% if user_signed_in? && current_user.can_update?(schedule) %>
              <%= link_to icon_button('edit', kind: :info), edit_schedule_path(schedule) %>
            <% end %>
            <% if user_signed_in? && current_user.can_delete?(schedule) %>
              <%= link_to icon_button('trash', kind: :danger), schedule, method: :delete, data: { confirm: 'Are you sure?' } %>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<%= will_paginate @schedules %>

<br>
<%= link_to far_icon_text('calendar-plus', '일정등록'), new_schedule_path, class: 'btn btn-success' %>

app/views/schedules/new.html.erb
<h2>일정등록</h2>
<br />
<%= render 'form' %>

app/views/schedules/show.html.erb
<h2>일정보기</h2>
<br />

<div class="well">
  <div class='markdown-preview' style='border-radius:5px;padding:1em;'>
    <%= @schedule.info %>
  </div>
</div>

<% if user_signed_in? && current_user.has_role?(:admin) %>
  <div class="panel panel-default table-responsive">
    <table class='table table-bordered'>
      <tr>
        <th class='text-right'><%= t("activerecord.attributes.schedule.name") %></th>
        <td class='text-danger'><strong><%= @schedule.name %></strong></td>
      </tr>
      <tr>
        <th class='text-right'><%= t("activerecord.attributes.schedule.venue") %></th>
        <td><%= @schedule.venue %></td>
      </tr>
      <tr>
        <th class='text-right'><%= t("activerecord.attributes.schedule.start_date") %></th>
        <td><%= @schedule.start_date %></td>
      </tr>
      <tr>
        <th class='text-right'><%= t("activerecord.attributes.schedule.end_date") %></th>
        <td><%= @schedule.end_date %></td>
      </tr>
      <tr>
        <th class='text-right'><%= t("activerecord.attributes.schedule.repeating") %></th>
        <td><%= yesno @schedule.repeating %></td>
      </tr>
      <tr>
        <th class='text-right'><%= t("activerecord.attributes.schedule.charged") %></th>
        <td><%= lecture_type @schedule.charged %></td>
      </tr>
      <tr>
        <th class='text-right'><%= t("activerecord.attributes.schedule.charge_amount") %></th>
        <td><%= number_to_currency @schedule.charge_amount %></td>
      </tr>
      <tr>
        <th class='text-right col-xs-2'><%= t("activerecord.attributes.schedule.user") %></th>
        <td><%= @schedule.user.email %> (<%= @schedule.created_at %>)</td>
      </tr>
    </table>
  </div>
<% end %>

<div class="form-actions">
  <%= link_to awesome_icon_label("edit", t("form_actions.edit")), edit_schedule_path(@schedule), class: 'btn btn-default' if user_signed_in? && current_user.can_update?(@schedule) %>
  <%= link_to awesome_icon_label("calendar","RORLAB일정"), schedules_path, class: 'btn btn-default' %>
  <%= link_to far_icon_text('list', "접수상황"), schedule_appliers_path(@schedule), class: 'btn btn-default' if user_signed_in? && current_user.can_update?(@schedule)%>
  <%= link_to far_icon_text('user-plus', '참가신청'), new_schedule_applier_path(@schedule), class: 'btn btn-success' %>
</div>

<!-- 댓글 위젯 -->
<%= render partial: "comments/comments_widget", locals: { resource: @schedule} %>