config/routes.rb
Rails.application.routes.default_url_options[:host] = 'rorlab.org'

Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root "welcome#index"

  get 'newsletters/unsubscribe/:email' => 'newsletters#unsubscribe', as: :eunsubscribe_newsletters
  get 'newsletters/subscribe/(:email)' => 'newsletters#subscribe'
  post 'newsletters/subscribe/(:email)' => 'newsletters#subscribe', as: :esubscribe_newsletters
  post 'newsletters/:user_id/subscribe' => 'newsletters#subscribe', as: :subscribe_newsletters
  put 'newsletters/:user_id/unsubscribe' => 'newsletters#unsubscribe', as: :unsubscribe_newsletters
  get 'newsletters/new/subscribe' => 'newsletters#new_subscribe', as: :new_subscribe_newsletters
  resources :newsletters do
    member do
      get 'preview'
      get 'sendmail'
    end
    resources :articles
  end


  post 'glossaries/:glossary_id/glossary_definitions/:id/like_toggle' => 'glossary_definitions#like_toggle', as: :like_glossary_definition
  match "/delayed_job" => DelayedJobWeb, :anchor => false, via: [:get, :post]

  get 'tags', to: 'tags#list'
  get 'purchase_requests/confirm_request/:id' => 'purchase_requests#confirm_request_toggle', as: :confirm_purchase

  # Info routing
  get 'info/about', as: :about
  get 'info/howto', as: :howto
  get 'info/copyright', as: :copyright
  get 'info/security', as: :security
  get 'info/contributor', as: :contributors

  get 'podcasts/grap' => 'podcasts#grap'
  get 'events/upcoming'
  # Exception routing
  get '/404', to: 'errors#not_found'
  get '/500', to: 'errors#server_error'

  # Devise routing
  devise_for :users, controllers: { registrations: 'users/registrations' }
  resource :user_profile

  # Resources routing
  resources :schedules do
    resources :appliers do
      member do
        put 'accept'
        put 'recommand'
      end
    end
  end

  concern :commentable do
    resources :comments
  end
  resources :favlinks, :codebanks, :rblogs, :events, :purchase_requests, :group_purchases, :courses, :lectures, :schedules, :websites, concerns: :commentable

  resources :glossaries, concerns: :commentable do
    member do
      post 'tag'
    end
    resources :glossary_definitions
  end

  resources :courses do
    resources :lectures
  end

  resources :group_purchases do
    resources :purchase_requests
  end

  resources :plazas
  resources :bundlelinks do
    resources :favlinks
  end
  resources :favlinks
  resources :bulletins do
    resources :posts
  end
  resources :questions do
    resources :answers
  end

  resources :podcasts, only: [ :index, :show ], concerns: :commentable

  get 'weeklynews/index', as: 'weeklynews'
  get 'weeklynews/grap', as: 'weeklynews_grap'


  # API routing
  namespace :api do
    resources :questions do
      resources :answers
    end
  end

end

app/models/applier.rb
# == Schema Information
#
# Table name: appliers
#
#  id          :integer          not null, primary key
#  schedule_id :integer
#  user_id     :integer
#  name        :string(255)      not null
#  email       :string(255)      not null
#  cellphone   :string(255)
#  remittor    :string(255)
#  remit_date  :datetime
#  remit_money :integer          default(0)
#  memo        :text(65535)
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  accepted    :boolean          default(FALSE)
#

class Applier < ActiveRecord::Base

  resourcify
  include Authority::Abilities

  belongs_to :schedule
  has_many :recommandations, dependent: :destroy
  has_many :recommanders, class_name: 'User', foreign_key: :recommander_id, through: :recommandations
  has_many :categories
  belongs_to :user

  validates :name, :email, presence: true
  validates :user_id, presence: true, uniqueness:  { scope: :schedule_id, message: "이미 신청하셨습니다." }

  scope :accepted, -> { where accepted: true }

  def recommanded_by?(user)
    self.recommanders.include? user
  end

end

app/controllers/appliers_controller.rb
# == Schema Information
#
# Table name: appliers
#
#  id          :integer          not null, primary key
#  schedule_id :integer
#  user_id     :integer
#  name        :string(255)      not null
#  email       :string(255)      not null
#  cellphone   :string(255)
#  remittor    :string(255)
#  remit_date  :datetime
#  remit_money :integer          default(0)
#  memo        :text(65535)
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  accepted    :boolean          default(FALSE)
#

class AppliersController < ApplicationController
  before_action :authenticate_user!, except: [:index]
  before_action :set_schedule
  before_action :set_applier, only: [:show, :edit, :update, :destroy, :accept, :recommand]

  def index
    # @schedule = Schedule.find(params[:schedule_id])
    @appliers = @schedule.appliers.order( created_at: :desc).paginate(page: params[:page], per_page: 10)
    @my_applier = current_user.appliers.find_by_schedule_id(@schedule.id) if user_signed_in?
  end

  def show
  end

  def new
    if @schedule.pre_start_date && Time.now < @schedule.pre_start_date
      flash[:error] =  '죄송합니다. 2016-05-23 00:00:00 +0900 부터 신청가능합니다. '
      redirect_to schedule_appliers_path(@schedule) and return
    end
    if @schedule.pre_end_date && Time.now >= @schedule.pre_end_date
      flash[:error] =  '죄송합니다. 사전등록이 마감되었습니다.  '
      redirect_to schedule_appliers_path(@schedule) and return
    end
    authorize_action_for Applier
    if @schedule.appliers.map(&:user).include?(current_user)
      @applier = current_user.appliers.find_by('schedule_id', @schedule)
      redirect_to edit_schedule_applier_path(@schedule, @applier), notice: '회원님은 이미 등록하셨습니다. 변경을 원하시면 수정 후 저장하시면 됩니다.' and return
    else
      @applier = @schedule.appliers.new(user_id: current_user.id, email: current_user.email)
    end
  end

  def edit
  end

  def create
    if @schedule.pre_start_date && Time.now < @schedule.pre_start_date
      flash[:error] =  '죄송합니다. 2016-05-23 00:00:00 +0900 부터 신청가능합니다. '
      redirect_to schedule_appliers_path(@schedule) and return
    end
    if @schedule.pre_end_date && Time.now >= @schedule.pre_end_date
      flash[:error] =  '죄송합니다. 사전등록이 마감되었습니다.  '
      redirect_to schedule_appliers_path(@schedule) and return
    end
    @applier = @schedule.appliers.new(applier_params)
    authorize_action_for Applier
    @applier.user = current_user

    respond_to do |format|
      if @applier.save
        UserMailer.confirm_application(current_user, @applier).deliver_later
        format.html { redirect_to [@schedule, @applier], notice: '신청접수가 완료되었습니다. 잠시후 확인메일이 발송됩니다.' }
        format.json { render :show, status: :created, location: @applier }
      else
        format.html { render :new }
        format.json { render json: @applier.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    authorize_action_for @applier
    respond_to do |format|
      if @applier.update(applier_params)
        format.html { redirect_to [@schedule, @applier], notice: '접수내용이 변경되었습니다. ' }
        format.json { render :show, status: :created, location: @applier }
      else
        format.html { render :new }
        format.json { render json: @applier.errors, status: :unprocessable_entity }
      end
    end

  end

  def destroy
    authorize_action_for @applier
    @applier.destroy
    UserMailer.confirm_application_withdraw(current_user).deliver_later
    respond_to do |format|
      format.html { redirect_to schedule_appliers_url, notice: '신청 취소되었습니다.' }
      format.json { head :no_content }
    end
  end

  def accept
    authorize_action_for @applier
    @applier.toggle! :accepted
    UserMailer.confirm_application_accept(current_user, @applier).deliver_later if @applier.accepted
    respond_to do |format|
      format.html { redirect_to [@schedule, @applier], notice: ( @applier.accepted ? "최종승인되었습니다." : "승인취소되었습니다.")}
      format.json { render json: @applier }
      format.js
    end
  end

  def recommand
    authorize_action_for @applier
    if @applier.recommanded_by? current_user
      @applier.recommanders.delete current_user
    else
      @applier.recommanders << current_user
    end
    respond_to do |format|
      format.html { redirect_to [@schedule, @applier], notice: ( @applier.accepted ? "추천했습니다." : "추천을 취소했습니다.")}
      format.json { render json: @applier }
      format.js
    end
  end


  private

  def set_schedule
    @schedule = Schedule.find(params[:schedule_id])
  end

  def set_applier
    @applier = @schedule.appliers.find(params[:id])
  end

  def applier_params
    params.require(:applier).permit(:schedule_id, :id, :name, :email, :cellphone, :remittor, :remit_date, :remit_money, :memo, :accepted)
  end

end

app/helpers/appliers_helper.rb
# == Schema Information
#
# Table name: appliers
#
#  id          :integer          not null, primary key
#  schedule_id :integer
#  user_id     :integer
#  name        :string(255)      not null
#  email       :string(255)      not null
#  cellphone   :string(255)
#  remittor    :string(255)
#  remit_date  :datetime
#  remit_money :integer          default(0)
#  memo        :text(65535)
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  accepted    :boolean          default(FALSE)
#

module AppliersHelper
end

app/views/appliers/_accept_state.html.erb
<%= link_to (applier.accepted ? awesome_icon('check-square-o') : awesome_icon('square')), accept_schedule_applier_path(applier.schedule, applier), method: :put, remote: true, data:{confirm:'Are you sure?'} %>

app/views/appliers/_applier.html.erb
<div class="panel panel-default table-responsive">
  <table class="table table-bordered">
    <tr>
      <th class='col-xs-2 text-right'><%= t("activerecord.attributes.applier.id") %></th>
      <td><%= applier.id %></td>
    </tr>
    <tr>
      <th class='col-xs-2 text-right'>
        <%= t("activerecord.attributes.applier.name") %>
      </th>
      <td>
        <%= link_to_if current_user == applier.user, image_tag(applier.user.user_profile&.avatar_url(:thumb).presence || 'contributors/generic-user.png', class:'profile'), ( applier.user.user_profile&.avatar_url(:thumb).present? ? edit_user_profile_path : new_user_profile_path ) %>
        <%= applier.name %>
        <span class='text-success'><%= awesome_icon_label "check-square-o", "최종수락" if applier.accepted %></span>
      </td>
    </tr>
    <tr>
      <th class='text-right'><%= t("activerecord.attributes.applier.email") %></th>
      <td><%= applier.email %></td>
    </tr>
    <tr>
      <th class='text-right'><%= t("activerecord.attributes.applier.cellphone") %></th>
      <td><%= applier.cellphone %></td>
    </tr>
    <tr>
      <th class='text-right'><%= t("activerecord.attributes.applier.created_at") %></th>
      <td><%= applier.created_at %></td>
    </tr>
    <% if applier.schedule.charged  %>
      <tr>
        <th class='text-right'><%= t("activerecord.attributes.applier.remittor") %></th>
        <td><%= applier.remittor %></td>
      </tr>
      <tr>
        <th class='text-right'><%= t("activerecord.attributes.applier.remit_date") %></th>
        <td><%= applier.remit_date %></td>
      </tr>
      <tr>
        <th class='text-right'><%= t("activerecord.attributes.applier.remit_money") %></th>
        <td><%= applier.remit_money %></td>
      </tr>
    <% end %>
    <tr>
      <th class='text-right'><%= t("activerecord.attributes.applier.memo") %></th>
      <td>
        <%#= applier.memo %>
        <div class='markdown-preview'>
          <%= applier.memo %>
        </div>
      </td>
    </tr>
  </table>
</div>

app/views/appliers/_form.html.erb
<%= render "layouts/shared/preview", title: "#{@applier.name}님의 자기소개", attribute: :memo %>


<%= simple_form_for [@schedule, @applier] do | f | %>
  <%= f.error_notification %>
  <ul>
  <% @applier.errors.messages.each do |message| %>
    <% if message[0] == :user_id %>
    <li><%= message[1][0]  %></li>
    <% end %>
  <% end %>
  </ul>
  <%= f.input :name %>
  <%= f.input :email %>
  <%= f.input :cellphone %>
  <% if @schedule.charged %>
    <%= f.input :remittor %>
    <%= f.input :remit_date %>
    <%= f.input :remit_money %>
  <% end %>
  <%= f.input :memo, :as => :pagedown, input_html: { rows: 17 }  %>

  <div class="alert alert-success">
    <%= awesome_icon("exclamation-triangle") %> 반드시 설문지를 충실히 작성해 주셔야 합니다. <%= link_to "설문지 작성하기", "http://goo.gl/forms/kjpdDM7y3yy83ayu2", target: '_blank', class: 'btn btn-success btn-xs' %>
  </div>

  <div class="form-actions">
    <%= button_tag(type: 'submit', class: "btn btn-success") do %>
      <%= awesome_icon_label "save", "저장" %>
    <% end %>
    <%= link_to far_icon_text('list', "접수상황"), schedule_appliers_path(@schedule), class: 'btn btn-default' %>
  </div>
<% end %>

app/views/appliers/_recommand_state.html.erb
<%= link_to (applier.recommanded_by?(current_user) ? awesome_icon('check-square-o') : awesome_icon('square')), recommand_schedule_applier_path(applier.schedule, applier), method: :put, remote: true, data:{confirm:'Are you sure?'} %>
<%= applier.recommanders.size %>

app/views/appliers/accept.js.erb
$("#accept_state_of_<%= @applier.id %>").html("<%=j render(partial: 'accept_state', locals: { applier: @applier }) %>")

app/views/appliers/edit.html.erb
<h2>신청변경</h2>
<br />
<%= render 'form' %>

app/views/appliers/index.html.erb
<br />

<% if Time.now < @schedule.pre_end_date %>
<div class="well alert">
    <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
  <div class='markdown-preview' style='border-radius:5px;padding:1em;'>
    <%= @schedule.info %>
  </div>
</div>
<% end %>

<% if @my_applier %>
<div class='alert alert-info'>
  <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
  <h2>신청접수상황</h2>
    <%= render partial: 'applier', locals: { applier: @my_applier} %>
  </div>
<% end %>

<% if user_signed_in? && current_user.has_role?(:contributor) %>
<h2>신청자명단 <small><%= @schedule.name %></small></h2>
<br />

<p>
  사전등록 : 총 <%= @schedule.appliers.size %> 명 |
  최종수락 : 총 <%= @schedule.appliers.accepted.size %> 명
</p>

<div class="panel panel-default table-responsive">
  <table class="table table-bordered">
    <thead>
      <tr>
        <th class='text-center'>신청자명</th>
        <th class='text-center'>이메일</th>
        <th class='text-center'>접수일</th>
        <th class='text-center'>추천</th>
        <th class='text-center'>최종수락</th>
        <th class='text-center'>데이터작업</th>
      </tr>
    </thead>
    <tbody>
    <% if @appliers.empty? %>
      <tr><td class='text-center text-primary' colspan='5'><%= awesome_icon_label "exclamation-triangle", '아직 참가 신청자가 없습니다.' %></td></tr>
    <% end %>
    <% @appliers.each do | applier | %>
      <tr>
        <td class='text-center'><%= applier.name %></td>
        <td class='text-center'><%= applier.email %></td>
        <td class='text-center'><%= applier.created_at %></td>
        <td id="recommand_state_of_<%= applier.id %>" class='text-center text-<%= applier.recommanded_by?(current_user) ? 'success' : 'muted' %>'>
          <%= render partial: 'recommand_state', locals: { applier: applier } %>
        </td>
        <td id="accept_state_of_<%= applier.id %>" class='text-center text-<%= applier.accepted ? 'success' : 'muted' %>'>
          <%= render partial: 'accept_state', locals: { applier: applier } %>
        </td>
        <td class='text-center'>
          <%= link_to icon_button('eye-open', :success), [applier.schedule, applier] %>
          <% if user_signed_in? && current_user.can_update?(applier) %>
            <%= link_to icon_button('edit', :info), edit_schedule_applier_path(applier.schedule, applier) %>
          <% end %>
          <% if user_signed_in? && current_user.can_delete?(applier) %>
            <%= link_to icon_button('trash', :danger), [applier.schedule, applier], method: :delete, data: { confirm: 'Are you sure?' } %>
          <% end %>
        </td>
      </tr>
    <% end %>
    </tbody>
  </table>
</div>
<center>
  <%= will_paginate @appliers %>
</center>
<% end %>


<br />
<% if @my_applier && current_user.can_update?(@my_applier)%>
  <%= link_to awesome_icon_label("edit","수정"), edit_schedule_applier_path(@schedule, @my_applier), class: 'btn btn-default' %>
  <%= link_to awesome_icon_label("eye",t("form_actions.show")), [@schedule, @my_applier], class: 'btn btn-default' %>
  <%= link_to awesome_icon_label("user-times","신청취소"), [@schedule, @my_applier], method: :delete, data:{confirm:"Are you sure?"}, class: 'btn btn-danger' %>
<% else %>
  <%= link_to awesome_icon_label("user-plus","참가신청"), new_schedule_applier_path(@schedule), class: 'btn btn-success' %>
<% end %>

<%= link_to awesome_icon_label("calendar","RORLAB일정"), schedules_path, class: 'btn btn-default' %>

app/views/appliers/new.html.erb
<h2>참가신청</h2>
<br />
<%= render 'form' %>

app/views/appliers/recommand.js.erb
$("#recommand_state_of_<%= @applier.id %>").html("<%=j render(partial: 'recommand_state', locals: { applier: @applier }) %>")

app/views/appliers/show.html.erb
<h2>신청내용</h2>
<br />
<%= render partial: 'applier', locals: {applier: @applier }%>
<br />
<div class="form-actions">
  <%= link_to awesome_icon_label("check","신청확인"), schedule_appliers_path(@schedule), class: 'btn btn-default' %>
  <%= link_to fas_icon_text('edit', t("form_actions.edit")), edit_schedule_applier_path(@schedule, @applier), class: 'btn btn-default' %>
  <%= link_to (@applier.recommanded_by?(current_user) ? awesome_icon_label("user-times", "추천취소") : awesome_icon_label("user-plus", "추천")), recommand_schedule_applier_path(@schedule, @applier), method: :put, data:{confirm:'Are you sure?'}, class: "btn btn-#{ @applier.recommanded_by?(current_user) ? 'danger' : 'success'}" if current_user.can_accept?(@applier)%>
  <%= link_to (@applier.accepted ? awesome_icon_label("user-times", "수락취소") : awesome_icon_label("user-plus", "최종수락")), accept_schedule_applier_path(@schedule, @applier), method: :put, data:{confirm:'Are you sure?'}, class: "btn btn-#{ @applier.accepted ? 'danger' : 'success'}" if current_user.can_accept?(@applier)%>
</div>