config/routes.rb
Rails.application.routes.default_url_options[:host] = 'rorlab.org'

Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root "welcome#index"

  get 'newsletters/unsubscribe/:email' => 'newsletters#unsubscribe', as: :eunsubscribe_newsletters
  get 'newsletters/subscribe/(:email)' => 'newsletters#subscribe'
  post 'newsletters/subscribe/(:email)' => 'newsletters#subscribe', as: :esubscribe_newsletters
  post 'newsletters/:user_id/subscribe' => 'newsletters#subscribe', as: :subscribe_newsletters
  put 'newsletters/:user_id/unsubscribe' => 'newsletters#unsubscribe', as: :unsubscribe_newsletters
  get 'newsletters/new/subscribe' => 'newsletters#new_subscribe', as: :new_subscribe_newsletters
  resources :newsletters do
    member do
      get 'preview'
      get 'sendmail'
    end
    resources :articles
  end


  post 'glossaries/:glossary_id/glossary_definitions/:id/like_toggle' => 'glossary_definitions#like_toggle', as: :like_glossary_definition
  match "/delayed_job" => DelayedJobWeb, :anchor => false, via: [:get, :post]

  get 'tags', to: 'tags#list'
  get 'purchase_requests/confirm_request/:id' => 'purchase_requests#confirm_request_toggle', as: :confirm_purchase

  # Info routing
  get 'info/about', as: :about
  get 'info/howto', as: :howto
  get 'info/copyright', as: :copyright
  get 'info/security', as: :security
  get 'info/contributor', as: :contributors

  get 'podcasts/grap' => 'podcasts#grap'
  get 'events/upcoming'
  # Exception routing
  get '/404', to: 'errors#not_found'
  get '/500', to: 'errors#server_error'

  # Devise routing
  devise_for :users, controllers: { registrations: 'users/registrations' }
  resource :user_profile

  # Resources routing
  resources :schedules do
    resources :appliers do
      member do
        put 'accept'
        put 'recommand'
      end
    end
  end

  concern :commentable do
    resources :comments
  end
  resources :favlinks, :codebanks, :rblogs, :events, :purchase_requests, :group_purchases, :courses, :lectures, :schedules, :websites, concerns: :commentable

  resources :glossaries, concerns: :commentable do
    member do
      post 'tag'
    end
    resources :glossary_definitions
  end

  resources :courses do
    resources :lectures
  end

  resources :group_purchases do
    resources :purchase_requests
  end

  resources :plazas
  resources :bundlelinks do
    resources :favlinks
  end
  resources :favlinks
  resources :bulletins do
    resources :posts
  end
  resources :questions do
    resources :answers
  end

  resources :podcasts, only: [ :index, :show ], concerns: :commentable

  get 'weeklynews/index', as: 'weeklynews'
  get 'weeklynews/grap', as: 'weeklynews_grap'


  # API routing
  namespace :api do
    resources :questions do
      resources :answers
    end
  end

end

app/views/layouts/shared/sidebar/_my_bundles.html.erb
<% if user_signed_in? %>
  <div class='row'>
    <div class='col-md-12'>
      <p><%= link_to_if (user_signed_in? && current_user.has_role?(:user)), "My Bundlelinks :", bundlelinks_path %></p>
      <ul class='fa-ul ml-4'>
      <% bundles = Bundlelink.my_private_bundles(current_user) %>
      <% bundles.each do |bundle| %>
        <li>
          <span class="fa-li text-<%= bundle.shared ? 'success' : 'danger' %>">
            <%= fas_icon_shared(bundle.shared) %>
          </span>
          <%= link_to bundle.title, bundlelink_favlinks_path(bundle)%> (<%= bundle.favlinks.size %>)
        </li>
      <% end %>
      </ul>
    </div>
  </div>
<% end %>

app/views/layouts/shared/sidebar/_my_codes.html.erb
<% if user_signed_in? %>
  <div class='row'>
    <div class='col-md-12'>
      <p><%= link_to_if (user_signed_in? && current_user.has_role?(:user)), "All Shared Snippets ", codebanks_path %><small>(<%= Codebank.shared.size %>)</small></p>
      <p><%= link_to_if (user_signed_in? && current_user.has_role?(:user)), "My Shared Snippets ", codebanks_path(whose: current_user.id) %><small>(<%= Codebank.my_shared_snippets(current_user.id).size %>)</small></p>
      <p><%= link_to_if (user_signed_in? && current_user.has_role?(:user)), "My Private Snippets ", codebanks_path(whose: current_user.id, private: 1) %><small>(<%= Codebank.my_private_snippets(current_user.id).size %>)</small></p>
      <ul class='fa-ul ml-4'>
      <% codbanks = Codebank.my_private_snippets(current_user.id) %>
      <% codbanks.each do |snippet| %>
        <li>
          <span class="fa-li text-<%= snippet.shared ? 'success' : 'danger' %>">
            <%= fas_icon_shared(snippet.shared) %>
          </span>
          <%= link_to truncate(snippet.title), codebank_path(snippet)%>
        </li>
      <% end %>
      </ul>
    </div>
  </div>
<% end %>

app/views/layouts/shared/sidebar/_my_posts.html.erb
<% if user_signed_in? %>
  <div class='row'>
    <div class='col-md-12'>
      <p><strong>My Posts <small>(<%= Post.my_posts(current_user.id).size %>)</small></strong></p>
      <ul style="list-style-type: none;padding-left:1.5rem;">
      <% Post.my_posts(current_user).each do |post| %>
        <li style='text-indent:-.5rem;'><%= fas_icon_shared(post.published).html_safe %> <%= link_to "#{post.bulletin.title} / #{truncate(post.title, length: 20)}", [post.bulletin, post] %></li>
      <% end %>
      </ul>

    </div>
  </div>
<% end %>

app/views/layouts/shared/sidebar/_my_rblogs.html.erb
<% if user_signed_in? %>
  <div class='row'>
    <div class='col-md-12'>
      <p><%= link_to_if (user_signed_in? && current_user.has_role?(:user)), "All Shared rBlogs ", rblogs_path %><small>(<%= Rblog.shared.size %>)</small></p>
      <p><%= link_to_if (user_signed_in? && current_user.has_role?(:user)), "My Shared rBlogs ", rblogs_path(whose: current_user.id) %><small>(<%= Rblog.my_shared_blogs(current_user.id).size %>)</small></p>
      <p><%= link_to_if (user_signed_in? && current_user.has_role?(:user)), "My Private rBlogs ", rblogs_path(whose: current_user.id, private: 1) %><small>(<%= Rblog.my_private_blogs(current_user.id).size %>)</small></p>
      <ul class='fa-ul ml-4'>
      <% rblogs = Rblog.my_private_blogs(current_user.id) %>
      <% rblogs.each do |blog| %>
        <li>
          <span class="fa-li text-<%= blog.shared ? 'success' : 'danger' %>">
            <%= fas_icon_shared(blog.shared) %>
          </span>
          <%= link_to truncate(blog.title), rblog_path(blog)%>
        </li>
      <% end %>
      </ul>
    </div>
  </div>
<% end %>

app/views/layouts/shared/sidebar/_sidebar_for_codebanks.html.erb
<% if controller_name == 'codebanks' %>
<div>
  <p style="margin-top:2rem;margin-bottom:2em;border:1px solid red; border-radius:5px;padding:1em;">
    <%= link_to image_tag("codebank_no_border.png", width: '100%'), codebanks_path(page:nil, search:nil) %>
    <%= link_to fas_icon_text('plus', '코드작성'), new_codebank_path, class: "btn btn-danger #{'disabled' if action_name == 'new'}", style:'margin-top:1em;display:block;'%>
  </p>

  <%= render "layouts/shared/sidebar/my_codes" %>
</div>
<% end %>

app/views/layouts/shared/sidebar/_sidebar_for_lectures.html.erb
<% if controller_name == 'courses' or controller_name == 'lectures' %>
  <div>
    <p style="margin-top:2rem;margin-bottom:2em;border:1px solid red; border-radius:5px;padding:1em;">
      <%= link_to image_tag("lecture_no_border.png", width: '100%'), courses_path(page:nil, search:nil) %>
      <%= link_to fas_icon_text('plus', '강좌개설'), new_course_path, class: "btn btn-danger #{'disabled' if action_name == 'new'}", style:'margin-top:1em;display:block;'%>
    </p>
    <%= render "layouts/shared/sidebar/my_rblogs" %>
  </div>
<% end %>

app/views/layouts/shared/sidebar/_sidebar_for_newsletters.html.erb
<% if controller_name == 'newsletters' %>
  <div>
    <p style="margin-top:2rem;margin-bottom:2em;border:1px solid red; border-radius:5px;padding:1em;">
      <%= link_to image_tag("newsletter_no_border.png", width: '100%'), newsletters_path(page:nil, search:nil) %>
      <%= link_to fas_icon_text('plus', '기사추가'), Newsletter.last, class: "btn btn-danger #{'disabled' if action_name == 'new'}", style:'margin-top:1em;display:block;'%>
    </p>

    <div id='subscribing_state_of_newsletters'>
      <%= render 'newsletters/subscribing_state_of_newsletters' unless action_name == 'new_subscribe' %>
    </div>

  </div>
<% end %>

app/views/layouts/shared/sidebar/_sidebar_for_posts.html.erb
<% if controller_name == 'posts' %>
  <div style="">
    <%= link_to fas_icon('plus', text: 'Add a Post'), new_bulletin_post_path(params[:bulletin_id]), 'data-turbolinks': false, class: 'btn btn-outline-primary btn-block' %>
  </div>
  <div class='mt-4'>
    <%= render "layouts/shared/sidebar/my_posts" %>
  </div>

<% end %>

app/views/layouts/shared/sidebar/_sidebar_for_questions.html.erb
<% if controller_name == 'questions' %>
  <p style="margin-top:2rem;margin-bottom:2em;border:1px solid red; border-radius:5px;padding:1em;">
    <%= link_to image_tag("q_&_a_no_border.png", width: '100%'), questions_path(page:nil, search:nil) %>
    <%= link_to fas_icon_text('plus', '질문 등록'), new_question_path, class: "btn btn-danger #{'disabled' if action_name == 'new'}", style:'margin-top:1em;display:block;'%>
  </p>
<% end %>

app/views/layouts/shared/sidebar/_sidebar_for_rblogs.html.erb
<% if controller_name == 'rblogs' %>
  <div>
    <p style="margin-top:2rem;margin-bottom:2em;border:1px solid red; border-radius:5px;padding:1em;">
      <%= link_to image_tag("rblog_no_border.png", width: '100%'), rblogs_path(page:nil, search:nil) %>
      <%= link_to fas_icon_text('plus', '새글작성'), new_rblog_path, class: "btn btn-danger #{'disabled' if action_name == 'new'}", style:'margin-top:1em;display:block;'%>
    </p>
    <%= render "layouts/shared/sidebar/my_rblogs" %>
  </div>
<% end %>

app/views/layouts/shared/sidebar/_sidebar_for_twitter.html.erb
<div class="d-hidden d-md-block border rounded" style="height: 50rem; overflow: auto;">
  <a class="twitter-timeline" href="https://twitter.com/rorlab?ref_src=twsrc%5Etfw">Tweets by rorlab</a> 
  <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
</div>

app/views/layouts/shared/sidebar/_sidebar_for_websites.html.erb
<% if controller_name == 'websites' %>
<div>
  <p style="margin-top:2rem;margin-bottom:2em;border:1px solid red; border-radius:5px;padding:1em;">
    <%= link_to image_tag("rails_sites.png", width: '100%'), websites_path(page:nil, search:nil) %>
    <%= link_to fas_icon_text('plus', '서비스추가'), new_website_path, class: "btn btn-danger #{'disabled' if action_name == 'new'}", style:'margin-top:1em;display:block;'%>
  </p>
</div>
<% end %>

app/views/layouts/shared/sidebar/_tag_clouds.html.erb
<% @tags = Favlink.tag_counts_on(:tags) if @tags.blank? %>
<p>Tag Cloud :</p>
<% tag_cloud(@tags, %w(css1 css2 css3 css4)) do |tag, css_class| %>
  <span class='badge badge-default'><%= link_to tag.name, favlinks_path(tag: tag.name), :class => css_class %></span>
<% end %>

app/views/layouts/shared/sidebar/_tag_clouds_for_favlink.html.erb
<% @tags = Favlink.tag_counts_on(:tags) if @tags.blank? %>
<p>Tag Cloud :</p>
<% tag_cloud(@tags, %w(css1 css2 css3 css4)) do |tag, css_class| %>
  <span class='badge badge-secondary'><%= link_to tag.name, favlinks_path(tag: tag.name), :class => css_class %></span>
<% end %>